TIMEOUT 10
DEFAULT mainline

MENU TITLE Mainline Linux (Nintendo Switch, HAC-001)

LABEL mainline
	MENU LABEL Mainline Linux, no serial console
	LINUX /boot/Image
	FDT /boot/tegra210-nintendo-switch.dtb
	APPEND root=/dev/mmcblk0p2 rw rootwait loglevel=3 fbcon=rotate:3 console=tty0

LABEL uart
	MENU LABEL Mainline Linux, console on ttyS1 (no right joycon)
	LINUX /boot/Image
	FDT /boot/tegra210-nintendo-switch-uartcon.dtb
	APPEND root=/dev/mmcblk0p2 rw rootwait loglevel=7 fbcon=rotate:3 console=ttyS1,115200n8 earlycon=uart8250,mmio32,0x70006040 printk.devkmsg=on no_console_suspend
