# uart debug:
# loglevel=7 console=ttyS2,1500000

TIMEOUT 10
DEFAULT gentoo-7.1

MENU TITLE MNT Pocket Reform

LABEL gentoo-7.1
	MENU LABEL gentoo-7.1
	LINUX /boot/7.1/vmlinuz
	FDT /boot/7.1/dtb
    APPEND root=PARTUUID=d0c06c42-58bb-4474-87d5-0ba6cfb0508b rw rootwait pcie_aspm=off loglevel=3

LABEL gentoo-6.19
	MENU LABEL gentoo-6.19
	LINUX /boot/6.19/vmlinuz
	FDT /boot/6.19/dtb
    APPEND root=PARTUUID=d0c06c42-58bb-4474-87d5-0ba6cfb0508b rw rootwait pcie_aspm=off loglevel=3 
