#!/bin/zsh

csi_num=0
sensor_width=3264
sensor_height=2448
width=3200
height=2200

wlcam_args=(
    --video-codec vp9_vaapi
    # --ffmpeg-debug
)

sensor_params=(
    "Red Balance"       1850
    "Blue Balance"      1550
    "Exposure"          2400
    "Horizontal Flip"   1
    "Vertical Flip"     0
    "Vertical Blanking" 40
    "Analogue Gain"     1024
)

on_ready() {
    swaymsg "splitv"

    "$vcw_bin" $lens_dev &
    sleep 0.1
    "$vcw_bin" $sensor_dev &
    sleep 0.1
    swaymsg "move down;resize shrink height 84 px;"
    sleep 0.1
    swaymsg "focus up;resize shrink height 140 px;resize shrink width 80 px;" > /dev/null # supress "Error: Cannot resize any further"
}

source ~/bin/wlcam-helper
open_wlcam
