#!/bin/zsh

csi_num=1
sensor_width=2592
sensor_height=1944
width=2560
height=1600
#width=1920
#height=1280

wlcam_args=(
    --video-codec vp9_vaapi
    --param "wb_gains.r"  5000
    --param "wb_gains.b"  6700
    --param "wb_gains.gr" 0
    --param "wb_gains.gb" 0
)

sensor_params=(
    "Exposure"          2400
    "Horizontal Flip"   0
    "Vertical Flip"     0
    "Vertical Blanking" 40
    "Analogue Gain"     1024
)

on_ready() {
    sleep 0.1
    swaymsg "splitv"
    $vcw_bin $sensor_dev &
    sleep 0.1
    swaymsg "move down; resize shrink height 56 px;"
    sleep 0.1
    swaymsg "focus up; resize shrink width 116 px;" > /dev/null # supress "Error: Cannot resize any further"
}

source ~/bin/wlcam-helper
open_wlcam
