#!/bin/zsh

scripts=/home/mojyack/build/gentoo-note/scripts

lid=$($scripts/find-input-device.sh "Lid Switch") || exit 1
kbd=$($scripts/find-input-device.sh "Apple SPI Keyboard") || exit 1
kbdled="/sys/class/leds/spi::kbd_backlight/brightness"

swaysock=$(ls /tmp/user/1000 | grep -E 'sway-ipc.*sock' 2>/dev/null)

if [[ -n $swaysock ]]; then
    dpms_on() {
        swaymsg -s "/tmp/user/1000/$swaysock" "output eDP-1 dpms on"
    }
    dpms_off() {
        swaymsg -s "/tmp/user/1000/$swaysock" "output eDP-1 dpms off"
    }
else
    dpms_on() {
        echo 1 > /sys/class/graphics/fb0/blank
    }
    dpms_off() {
        echo 0 > /sys/class/graphics/fb0/blank
    }
fi

dpms_off

kbdbackup=$(<$kbdled)
echo 0 > $kbdled

$scripts/blizzard/blizzard.sh "/dev/input/$lid" "/dev/input/$kbd"

# fix touchpad
modprobe -r applespi
modprobe applespi

dpms_on
echo $kbdbackup > $kbdled

exit 1 # prevent hardware suspend
