#!/bin/bash

ROOTFS=PARTUUID=${UUID}
CMDLINE="rw quiet loglevel=3 mitigations=off fsck.mode=skip nowatchdog"
KERNEL=/usr/src/linux

ENTRY_NAME=Gentoo Linux
BOOT_CONF=gentoo.conf
OLD_BOOT_CONF=gentoo.conf.old

echo -n "checking ${KERNEL} kernel version... "
cd "${KERNEL}"
kv="$(make kernelversion)"
image="vmlinuz-${kv}"
echo "${kv}"

echo -n "checking for /boot/${image}... "
if [[ -f /boot/${image} ]]; then
  echo "found"
else
  echo "not found"
  exit 1
fi

echo -n "checking for /lib/modules/${kv}/... "
if [[ -d /lib/modules/${kv}/ ]]; then
  echo "found"
else
  echo "not found"
  exit 1
fi

echo -n "backing up current systemd-boot boot entries... "
cd /boot/loader/entries
if grep -q "${kv}" ${BOOT_CONF}; then
  echo "skipped"
else
  sed -e 's/^title .*$/title ${ENTRY_NAME} (Previous)/' ${BOOT_CONF} > ${OLD_BOOT_CONF}
  echo "done"
fi

echo -n "generating systemd-boot boot entries... "
echo "title ${ENTRY_NAME}" > ${BOOT_CONF}
echo "linux /${image}" >> ${BOOT_CONF}
#echo "initrd /initramfs-${kv}.img" >> ${BOOT_CONF}
echo "options root=${ROOTFS} ${CMDLINE}" >> ${BOOT_CONF}
echo "done"
