if [[ -e /etc/profile.env ]] {
    . /etc/profile.env
}

if [[ "$HOME" == */ ]] {
    HOME=$(readlink -f "$HOME")
}

if [[ -z "$XDG_CONFIG_HOME" ]] {
    export XDG_CONFIG_HOME="$HOME/.config"
}

if [[ -d "$XDG_CONFIG_HOME/zsh" ]] {
    export ZDOTDIR="$XDG_CONFIG_HOME/zsh"
}

if [[ -z "$XDG_DATA_HOME" ]] {
    export XDG_DATA_HOME="$HOME/.local/share"
}

if [[ -z "$XDG_CACHE_HOME" ]] {
    export XDG_CACHE_HOME="$HOME/.cache"
}
